--- #YAML:1.0
name:               Hook-LexWrap
version:            0.22
abstract:           Lexically scoped subroutine wrappers
author:
    - Damian Conway (damian@conway.org)
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:  5.006
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
