---
abstract: 'Lexically scoped subroutine wrappers'
author:
  - 'Damian Conway (damian@conway.org)'
build_requires:
  Test::More: 0
generated_by: 'Module::Build version 0.3614'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hook-LexWrap
provides:
  Hook::LexWrap:
    file: lib/Hook/LexWrap.pm
    version: 0.24
  Hook::LexWrap::Cleanup:
    file: lib/Hook/LexWrap.pm
requires:
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/chorny/Hook-LexWrap
version: 0.24
